name: Build
run-name: ${{ github.ref_name }}/${{ github.sha }} 🚀
on: [push]
jobs:
    Build:  
      runs-on: windows-latest      
      steps:
        - uses: microsoft/setup-msbuild@v1.1
        - run: msbuild